global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:


scrape_configs:

  - job_name: "prometheus"

    static_configs:
      - targets:
        - localhost:9090
        - localhost:9115


  - job_name: 'ptsecurity'
    metrics_path: /probe

    params:
      module: [http_2xx]

    static_configs:
      - targets:
        - https://ptsecurity.com

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
